In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/shashikalarajesh11/data-and-time-dataset/orders (1).csv
/kaggle/input/datasets/shashikalarajesh11/data-and-time-dataset/messages.csv

In [2]:
import pandas as pd

## for time related work using messages.csv

In [3]:
df1=pd.read_csv('/kaggle/input/datasets/shashikalarajesh11/data-and-time-dataset/messages.csv')
df1.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

## For date related work using orders.csv

In [4]:
df2=pd.read_csv('/kaggle/input/datasets/shashikalarajesh11/data-and-time-dataset/orders (1).csv')
df2.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [6]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
df1['date']=pd.to_datetime(df1['date'])

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [9]:
df2['date']=pd.to_datetime(df2['date'])

In [10]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### Extract Year

In [11]:
df2['date_year']=df2['date'].dt.year

### Extract Month

In [12]:
df2['date_month']=df2['date'].dt.month

### Extract days

In [13]:
df2['date_days']=df2['date'].dt.day

### Extract Day of week

In [14]:
df2['date_day_of_week']=df2['date'].dt.dayofweek

### Extract name of the day

In [15]:
df2['date_name_of_day']=df2['date'].dt.day_name()

### Extract week number of the year

In [16]:
df2['Week_number']=df2['date'].dt.isocalendar().week

### Extract quarter

In [17]:
df2['quarter']=df2['date'].dt.quarter

### Extract Semester

In [18]:
df2['Semester']=np.where(df2['quarter'].isin([1,2]),1,2)

### Extract Time elapsed between dates

In [19]:
import datetime

today=datetime.datetime.today()
today

datetime.datetime(2026, 6, 12, 20, 17, 52, 424160)

In [20]:
today-df2['date']

0     2376 days 20:17:52.424160
1     2858 days 20:17:52.424160
2     2789 days 20:17:52.424160
3     2491 days 20:17:52.424160
4     2714 days 20:17:52.424160
                 ...
995   2804 days 20:17:52.424160
996   2745 days 20:17:52.424160
997   2593 days 20:17:52.424160
998   2658 days 20:17:52.424160
999   2432 days 20:17:52.424160
Name: date, Length: 1000, dtype: timedelta64[ns]

In [21]:
(today-df2['date']).dt.days

0      2376
1      2858
2      2789
3      2491
4      2714
       ...
995    2804
996    2745
997    2593
998    2658
999    2432
Name: date, Length: 1000, dtype: int64

In [22]:
df2.head()

,date,product_id,city_id,orders,date_year,date_month,date_days,date_day_of_week,date_name_of_day,Week_number,quarter,Semester
0,2019-12-10,5628,25,3,2019,12,10,1,Tuesday,50,4,2
1,2018-08-15,3646,14,157,2018,8,15,2,Wednesday,33,3,2
2,2018-10-23,1859,25,1,2018,10,23,1,Tuesday,43,4,2
3,2019-08-17,7292,25,1,2019,8,17,5,Saturday,33,3,2
4,2019-01-06,4344,25,3,2019,1,6,6,Sunday,1,1,1

In [23]:
import numpy as np

In [24]:
## is weekend

df2['date_is_Weekend']=np.where(df2['date_name_of_day'].isin(['Sunday','Saturday']),1,0)

In [25]:
df1['hour']=df1['date'].dt.hour
df1['Minute']=df1['date'].dt.minute
df1['second']=df1['date'].dt.second

In [26]:
df1.head()

,date,msg,hour,Minute,second
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0